--- #YAML:1.0
name:               Color-Model-RGB
version:            1.02
abstract:           Color model of RGB
author:
    - T.Onodera <ong@garakuta.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:              0
    Exporter:          0
    Math::VectorReal:  0
    POSIX:             0
    Scalar::Util:      0
    Test::More:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
