--- #YAML:1.0
name:                Color-Model-RGB
version:             1.01
abstract:            Color model of RGB
license:             perl
author:              
    - T.Onodera <ong@garakuta.net>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
